Index: usr.bin/mail/USD.doc/mail0.nr
===================================================================
RCS file: /home/ncvs/src/usr.bin/mail/USD.doc/mail0.nr,v
retrieving revision 1.1
retrieving revision 1.2
diff -u -I__FBSDID -r1.1 -r1.2
--- usr.bin/mail/USD.doc/mail0.nr	27 May 1994 12:32:07 -0000	1.1
+++ usr.bin/mail/USD.doc/mail0.nr	17 Aug 2005 15:56:04 -0000	1.2
@@ -66,6 +66,5 @@
 Version 5.5
 
 
-\*(td
 .)l
 .pn 2
